version: '3.8'
services:
  postgres:
    container_name: portfolioDb
    image: postgres:14.0-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: portfolio-rabbitmq-broker
    command: "rabbitmq-server"
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_VHOST=pla
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build:
      args:
        JAR_FILE: target/*.jar
      context: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8877:8877"
